version: 2
updates:
  - package-ecosystem: gomod
    directories:
      - /
      - /test
    schedule:
      interval: weekly
      day: wednesday
      time: "18:00"
    groups:
      k8s.io:
        patterns:
          - k8s.io/*
