version: "2"
run:
  build-tags:
    - e2e
linters:
  enable:
    - contextcheck
    - loggercheck
    - modernize
    - nolintlint
    - unconvert
    - usetesting
    - whitespace
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/nojnhuh/dra-driver-sandbox/
