apiVersion: resource.k8s.io/v1
kind: DeviceClass
metadata:
  name: test.template.example.com
spec:
  selectors:
  - cel:
      expression: device.driver == "template.example.com" &&
        device.attributes["template.example.com"].class == "test"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-devices
  labels:
    template.example.com/node-local-devices: ""
data:
  devices: |
    - name: dev0
      attributes:
        class:
          string: test
---
apiVersion: resource.k8s.io/v1
kind: ResourceClaim
metadata:
  name: one-device
spec:
    devices:
      requests:
      - name: dev
        exactly:
          deviceClassName: test.template.example.com
---
apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
  - name: ctr
    image: busybox
    restartPolicy: Never
    resources:
      claims:
      - name: claim
  resourceClaims:
  - name: claim
    resourceClaimName: one-device
