apiVersion: resource.k8s.io/v1
kind: DeviceClass
metadata:
  name: topology.sandbox.example.com
spec:
  selectors:
  - cel:
      expression: device.driver == "sandbox.example.com" &&
        device.attributes["sandbox.example.com"].class == "topology"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: topology-devices
  labels:
    sandbox.example.com/cluster-devices: ""
data:
  pool: topology
  nodeSelector: |
    nodeSelectorTerms:
    - matchExpressions:
      - key: kubernetes.io/hostname
        operator: Exists
  devices: |
    - name: topo0
      attributes:
        class:
          string: topology

---
apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: topology-domain
spec:
  spec:
    devices:
      requests:
      - name: dev
        exactly:
          deviceClassName: topology.sandbox.example.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: topology
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: ctr
        image: registry.k8s.io/pause:3.10.1
        resources:
          claims:
          - name: claim
      resourceClaims:
      - name: claim
        resourceClaimTemplateName: topology-domain
