apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dra-driver-sandbox-controller
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "create", "update"]
- apiGroups: ["resource.k8s.io"]
  resources: ["resourceslices"]
  verbs: ["list", "watch", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["list", "watch"]
