apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dra-driver-sandbox-kubeletplugin
  namespace: default
  labels:
    app.kubernetes.io/name: dra-driver-sandbox
    app.kubernetes.io/component: kubeletplugin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: dra-driver-sandbox
      app.kubernetes.io/component: kubeletplugin
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dra-driver-sandbox
        app.kubernetes.io/component: kubeletplugin
    spec:
      serviceAccountName: dra-driver-sandbox-kubeletplugin
      containers:
      - name: plugin
        image: dra-driver-sandbox
        imagePullPolicy: Never
        args:
          - -v=5
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        volumeMounts:
        - name: plugins-registry
          mountPath: /var/lib/kubelet/plugins_registry
        - name: plugins
          mountPath: /var/lib/kubelet/plugins
        - name: cdi
          mountPath: /var/run/cdi
      volumes:
      - name: plugins-registry
        hostPath:
          path: /var/lib/kubelet/plugins_registry
      - name: plugins
        hostPath:
          path: /var/lib/kubelet/plugins
      - name: cdi
        hostPath:
          path: /var/run/cdi
