apiVersion: v1
kind: ServiceAccount
metadata:
  name: dra-driver-sandbox-kubeletplugin
  namespace: default
  labels:
    app.kubernetes.io/name: dra-driver-sandbox
    app.kubernetes.io/component: kubeletplugin
