apiVersion: v1
kind: ServiceAccount
metadata:
  name: dra-driver-template-kubeletplugin
  namespace: default
  labels:
    app.kubernetes.io/name: dra-driver-template
    app.kubernetes.io/component: kubeletplugin
