name: Test
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.work
      - name: Run unit tests
        run: go test ./...
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.work
          cache-dependency-path: "**/go.mod"
      - parallel:
        - name: Build kubelet plugin image
          uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
          id: docker-build
          with:
            build-args: |
              cmd=dra-driver-sandbox-kubeletplugin
            tags: dra-driver-sandbox-kubeletplugin:latest
            load: true
        - name: Build controller image
          uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
          with:
            build-args: |
              cmd=dra-driver-sandbox-controller
            tags: dra-driver-sandbox-controller:latest
            load: true
        - name: Build kind node image
          id: kind-node
          run: |
            version=v1.36.2
            echo "version=${version}" >> "$GITHUB_OUTPUT"
            if ! docker manifest inspect "kindest/node:${version}"; then
              go run sigs.k8s.io/kind build node-image --image "kindest/node:${version}" --type release "${version}"
            fi
      - name: Run e2e tests
        run: go test -tags=e2e -artifacts ./test/e2e -run TestDriver/default --kubernetes-version "${{ steps.kind-node.outputs.version }}"
      - name: Upload artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: e2e-artifacts
          path: _artifacts
