name: Test
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: go.work
      - name: Run unit tests
        run: go test ./...
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Build driver image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        id: docker-build
        with:
          tags: dra-driver-sandbox:latest
          load: true
      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: go.work
      - name: Build kind node image
        id: kind-node
        run: |
          version=v1.36.2
          echo "version=${version}" >> "$GITHUB_OUTPUT"
          if ! docker manifest inspect "kindest/node:${version}"; then
            go run sigs.k8s.io/kind build node-image --image "kindest/node:${version}" --type release "${version}"
          fi
      - name: Run e2e tests
        run: go test -tags=e2e -artifacts ./test/e2e --kubernetes-version "${{ steps.kind-node.outputs.version }}"
      - name: Upload artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: e2e-artifacts
          path: _artifacts
